config/routes.rb
Rails.application.routes.draw do

  root 'statuses#index'
  get'help' => 'statuses#help'
  get 'contact' => 'statuses#contact'
  get 'about' => 'statuses#about'
  get 'feed'  => 'static_pages#show'
  get 'feed_all' => 'static_pages#show_all'
  get 'signup' => 'users#new'
  get 'login'  => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources  :comments
  resources  :statuses,  only: [:index,:show,:create, :destroy]
  resources :relationships, only: [:create, :destroy]

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="statuses">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_status_form.html.erb
<%= form_for(@status) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
  	<%= f.text_field  :title, placeholder: "compose new title..." %>
  </div>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new status..." %>
  </div>
  <div class="poststatus">
  	<%= f.submit "Post", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user), current_user %>

<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.statuses.count, "status") %></span>